//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneOfCustoms.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CustomerServiceSoap")]
    public interface CustomerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOrderData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendOrderData(SceneOfCustoms.ServiceReference1.OrderEn[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOrderData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendOrderDataAsync(SceneOfCustoms.ServiceReference1.OrderEn[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveDeclarationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SceneOfCustoms.ServiceReference1.DeclStatusEn[] ReceiveDeclarationStatus(string repno, string busiUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveDeclarationStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SceneOfCustoms.ServiceReference1.DeclStatusEn[]> ReceiveDeclarationStatusAsync(string repno, string busiUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveDeclaration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SceneOfCustoms.ServiceReference1.DeclarationEn[] ReceiveDeclaration(string repno, string busiUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveDeclaration", ReplyAction="*")]
        System.Threading.Tasks.Task<SceneOfCustoms.ServiceReference1.DeclarationEn[]> ReceiveDeclarationAsync(string repno, string busiUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveDeclarationPdf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SceneOfCustoms.ServiceReference1.DeclPdfEn[] ReceiveDeclarationPdf(string repno, string busiUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveDeclarationPdf", ReplyAction="*")]
        System.Threading.Tasks.Task<SceneOfCustoms.ServiceReference1.DeclPdfEn[]> ReceiveDeclarationPdfAsync(string repno, string busiUnit);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderEn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> sUBMITTIMEField;
        
        private int sUBMITUSERIDField;
        
        private string sUBMITUSERNAMEField;
        
        private string aRRIVEDNOField;
        
        private string dECLCARNOField;
        
        private string cONTAINERNOField;
        
        private string gOODSTYPEIDField;
        
        private string sECONDLADINGBILLNOField;
        
        private string fIRSTLADINGBILLNOField;
        
        private string mANIFESTField;
        
        private string wOODPACKINGIDField;
        
        private int wEIGHTCHECKField;
        
        private int iSWEIGHTCHECKField;
        
        private string sHIPNAMEField;
        
        private string fILGHTNOField;
        
        private string cLEARANCENOField;
        
        private int statusField;
        
        private FileEn[] filesField;
        
        private decimal idField;
        
        private string cODEField;
        
        private string cUSNOField;
        
        private string rEPNOField;
        
        private string eNTRUSTTYPEField;
        
        private string eNTRUSTTYPENAMEField;
        
        private string bUSITYPEField;
        
        private string bUSITYPENAMEField;
        
        private string rEPWAYIDField;
        
        private string rEPWAYNAMEField;
        
        private string cUSTOMAREACODEField;
        
        private string cUSTOMAREANAMEField;
        
        private string dECLWAYField;
        
        private string dECLWAYNAMEField;
        
        private string bUSIUNITCODEField;
        
        private string bUSIUNITNAMEField;
        
        private string bUSIUNITNUMField;
        
        private System.Nullable<decimal> gOODSNUMField;
        
        private System.Nullable<decimal> gOODSGWField;
        
        private System.Nullable<decimal> gOODSNWField;
        
        private string pACKKINDField;
        
        private string pACKKINDNAMEField;
        
        private string bELONGCUSTOMSField;
        
        private string bELONGCUSTOMSNAMEField;
        
        private string oRDERREQUESTField;
        
        private string rEPUNITCODEField;
        
        private System.Nullable<decimal> lAWFLAGField;
        
        private string dECLREPCODEField;
        
        private string dECLREPNAMEField;
        
        private string iNSPREPCODEField;
        
        private string iNSPREPNAMEField;
        
        private string tOTALNOField;
        
        private string dIVIDENOField;
        
        private string tURNPRENOField;
        
        private System.Nullable<decimal> pRODUCTNUMField;
        
        private string pORTCODEField;
        
        private string cORRESPONDNOField;
        
        private string aSSOCIATENOField;
        
        private System.Nullable<decimal> wEIGHTCONFIRMField;
        
        private string rECORDCODEField;
        
        private System.Nullable<decimal> iSINVALIDField;
        
        private System.Nullable<System.DateTime> cREATETIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> SUBMITTIME {
            get {
                return this.sUBMITTIMEField;
            }
            set {
                this.sUBMITTIMEField = value;
                this.RaisePropertyChanged("SUBMITTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SUBMITUSERID {
            get {
                return this.sUBMITUSERIDField;
            }
            set {
                this.sUBMITUSERIDField = value;
                this.RaisePropertyChanged("SUBMITUSERID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SUBMITUSERNAME {
            get {
                return this.sUBMITUSERNAMEField;
            }
            set {
                this.sUBMITUSERNAMEField = value;
                this.RaisePropertyChanged("SUBMITUSERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ARRIVEDNO {
            get {
                return this.aRRIVEDNOField;
            }
            set {
                this.aRRIVEDNOField = value;
                this.RaisePropertyChanged("ARRIVEDNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DECLCARNO {
            get {
                return this.dECLCARNOField;
            }
            set {
                this.dECLCARNOField = value;
                this.RaisePropertyChanged("DECLCARNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CONTAINERNO {
            get {
                return this.cONTAINERNOField;
            }
            set {
                this.cONTAINERNOField = value;
                this.RaisePropertyChanged("CONTAINERNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string GOODSTYPEID {
            get {
                return this.gOODSTYPEIDField;
            }
            set {
                this.gOODSTYPEIDField = value;
                this.RaisePropertyChanged("GOODSTYPEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SECONDLADINGBILLNO {
            get {
                return this.sECONDLADINGBILLNOField;
            }
            set {
                this.sECONDLADINGBILLNOField = value;
                this.RaisePropertyChanged("SECONDLADINGBILLNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FIRSTLADINGBILLNO {
            get {
                return this.fIRSTLADINGBILLNOField;
            }
            set {
                this.fIRSTLADINGBILLNOField = value;
                this.RaisePropertyChanged("FIRSTLADINGBILLNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MANIFEST {
            get {
                return this.mANIFESTField;
            }
            set {
                this.mANIFESTField = value;
                this.RaisePropertyChanged("MANIFEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string WOODPACKINGID {
            get {
                return this.wOODPACKINGIDField;
            }
            set {
                this.wOODPACKINGIDField = value;
                this.RaisePropertyChanged("WOODPACKINGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int WEIGHTCHECK {
            get {
                return this.wEIGHTCHECKField;
            }
            set {
                this.wEIGHTCHECKField = value;
                this.RaisePropertyChanged("WEIGHTCHECK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int ISWEIGHTCHECK {
            get {
                return this.iSWEIGHTCHECKField;
            }
            set {
                this.iSWEIGHTCHECKField = value;
                this.RaisePropertyChanged("ISWEIGHTCHECK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SHIPNAME {
            get {
                return this.sHIPNAMEField;
            }
            set {
                this.sHIPNAMEField = value;
                this.RaisePropertyChanged("SHIPNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FILGHTNO {
            get {
                return this.fILGHTNOField;
            }
            set {
                this.fILGHTNOField = value;
                this.RaisePropertyChanged("FILGHTNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CLEARANCENO {
            get {
                return this.cLEARANCENOField;
            }
            set {
                this.cLEARANCENOField = value;
                this.RaisePropertyChanged("CLEARANCENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public FileEn[] Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
                this.RaisePropertyChanged("Files");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CUSNO {
            get {
                return this.cUSNOField;
            }
            set {
                this.cUSNOField = value;
                this.RaisePropertyChanged("CUSNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string REPNO {
            get {
                return this.rEPNOField;
            }
            set {
                this.rEPNOField = value;
                this.RaisePropertyChanged("REPNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ENTRUSTTYPE {
            get {
                return this.eNTRUSTTYPEField;
            }
            set {
                this.eNTRUSTTYPEField = value;
                this.RaisePropertyChanged("ENTRUSTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ENTRUSTTYPENAME {
            get {
                return this.eNTRUSTTYPENAMEField;
            }
            set {
                this.eNTRUSTTYPENAMEField = value;
                this.RaisePropertyChanged("ENTRUSTTYPENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BUSITYPE {
            get {
                return this.bUSITYPEField;
            }
            set {
                this.bUSITYPEField = value;
                this.RaisePropertyChanged("BUSITYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string BUSITYPENAME {
            get {
                return this.bUSITYPENAMEField;
            }
            set {
                this.bUSITYPENAMEField = value;
                this.RaisePropertyChanged("BUSITYPENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string REPWAYID {
            get {
                return this.rEPWAYIDField;
            }
            set {
                this.rEPWAYIDField = value;
                this.RaisePropertyChanged("REPWAYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string REPWAYNAME {
            get {
                return this.rEPWAYNAMEField;
            }
            set {
                this.rEPWAYNAMEField = value;
                this.RaisePropertyChanged("REPWAYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CUSTOMAREACODE {
            get {
                return this.cUSTOMAREACODEField;
            }
            set {
                this.cUSTOMAREACODEField = value;
                this.RaisePropertyChanged("CUSTOMAREACODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string CUSTOMAREANAME {
            get {
                return this.cUSTOMAREANAMEField;
            }
            set {
                this.cUSTOMAREANAMEField = value;
                this.RaisePropertyChanged("CUSTOMAREANAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string DECLWAY {
            get {
                return this.dECLWAYField;
            }
            set {
                this.dECLWAYField = value;
                this.RaisePropertyChanged("DECLWAY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string DECLWAYNAME {
            get {
                return this.dECLWAYNAMEField;
            }
            set {
                this.dECLWAYNAMEField = value;
                this.RaisePropertyChanged("DECLWAYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string BUSIUNITCODE {
            get {
                return this.bUSIUNITCODEField;
            }
            set {
                this.bUSIUNITCODEField = value;
                this.RaisePropertyChanged("BUSIUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string BUSIUNITNAME {
            get {
                return this.bUSIUNITNAMEField;
            }
            set {
                this.bUSIUNITNAMEField = value;
                this.RaisePropertyChanged("BUSIUNITNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string BUSIUNITNUM {
            get {
                return this.bUSIUNITNUMField;
            }
            set {
                this.bUSIUNITNUMField = value;
                this.RaisePropertyChanged("BUSIUNITNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<decimal> GOODSNUM {
            get {
                return this.gOODSNUMField;
            }
            set {
                this.gOODSNUMField = value;
                this.RaisePropertyChanged("GOODSNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<decimal> GOODSGW {
            get {
                return this.gOODSGWField;
            }
            set {
                this.gOODSGWField = value;
                this.RaisePropertyChanged("GOODSGW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<decimal> GOODSNW {
            get {
                return this.gOODSNWField;
            }
            set {
                this.gOODSNWField = value;
                this.RaisePropertyChanged("GOODSNW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string PACKKIND {
            get {
                return this.pACKKINDField;
            }
            set {
                this.pACKKINDField = value;
                this.RaisePropertyChanged("PACKKIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string PACKKINDNAME {
            get {
                return this.pACKKINDNAMEField;
            }
            set {
                this.pACKKINDNAMEField = value;
                this.RaisePropertyChanged("PACKKINDNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string BELONGCUSTOMS {
            get {
                return this.bELONGCUSTOMSField;
            }
            set {
                this.bELONGCUSTOMSField = value;
                this.RaisePropertyChanged("BELONGCUSTOMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string BELONGCUSTOMSNAME {
            get {
                return this.bELONGCUSTOMSNAMEField;
            }
            set {
                this.bELONGCUSTOMSNAMEField = value;
                this.RaisePropertyChanged("BELONGCUSTOMSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string ORDERREQUEST {
            get {
                return this.oRDERREQUESTField;
            }
            set {
                this.oRDERREQUESTField = value;
                this.RaisePropertyChanged("ORDERREQUEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string REPUNITCODE {
            get {
                return this.rEPUNITCODEField;
            }
            set {
                this.rEPUNITCODEField = value;
                this.RaisePropertyChanged("REPUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public System.Nullable<decimal> LAWFLAG {
            get {
                return this.lAWFLAGField;
            }
            set {
                this.lAWFLAGField = value;
                this.RaisePropertyChanged("LAWFLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string DECLREPCODE {
            get {
                return this.dECLREPCODEField;
            }
            set {
                this.dECLREPCODEField = value;
                this.RaisePropertyChanged("DECLREPCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string DECLREPNAME {
            get {
                return this.dECLREPNAMEField;
            }
            set {
                this.dECLREPNAMEField = value;
                this.RaisePropertyChanged("DECLREPNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string INSPREPCODE {
            get {
                return this.iNSPREPCODEField;
            }
            set {
                this.iNSPREPCODEField = value;
                this.RaisePropertyChanged("INSPREPCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string INSPREPNAME {
            get {
                return this.iNSPREPNAMEField;
            }
            set {
                this.iNSPREPNAMEField = value;
                this.RaisePropertyChanged("INSPREPNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string TOTALNO {
            get {
                return this.tOTALNOField;
            }
            set {
                this.tOTALNOField = value;
                this.RaisePropertyChanged("TOTALNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string DIVIDENO {
            get {
                return this.dIVIDENOField;
            }
            set {
                this.dIVIDENOField = value;
                this.RaisePropertyChanged("DIVIDENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string TURNPRENO {
            get {
                return this.tURNPRENOField;
            }
            set {
                this.tURNPRENOField = value;
                this.RaisePropertyChanged("TURNPRENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public System.Nullable<decimal> PRODUCTNUM {
            get {
                return this.pRODUCTNUMField;
            }
            set {
                this.pRODUCTNUMField = value;
                this.RaisePropertyChanged("PRODUCTNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string PORTCODE {
            get {
                return this.pORTCODEField;
            }
            set {
                this.pORTCODEField = value;
                this.RaisePropertyChanged("PORTCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string CORRESPONDNO {
            get {
                return this.cORRESPONDNOField;
            }
            set {
                this.cORRESPONDNOField = value;
                this.RaisePropertyChanged("CORRESPONDNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string ASSOCIATENO {
            get {
                return this.aSSOCIATENOField;
            }
            set {
                this.aSSOCIATENOField = value;
                this.RaisePropertyChanged("ASSOCIATENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=56)]
        public System.Nullable<decimal> WEIGHTCONFIRM {
            get {
                return this.wEIGHTCONFIRMField;
            }
            set {
                this.wEIGHTCONFIRMField = value;
                this.RaisePropertyChanged("WEIGHTCONFIRM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string RECORDCODE {
            get {
                return this.rECORDCODEField;
            }
            set {
                this.rECORDCODEField = value;
                this.RaisePropertyChanged("RECORDCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=58)]
        public System.Nullable<decimal> ISINVALID {
            get {
                return this.iSINVALIDField;
            }
            set {
                this.iSINVALIDField = value;
                this.RaisePropertyChanged("ISINVALID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=59)]
        public System.Nullable<System.DateTime> CREATETIME {
            get {
                return this.cREATETIMEField;
            }
            set {
                this.cREATETIMEField = value;
                this.RaisePropertyChanged("CREATETIME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileEn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileTypeField;
        
        private byte[] fileContentField;
        
        private FileFormatEnum fileFormatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("FileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FileFormatEnum FileFormat {
            get {
                return this.fileFormatField;
            }
            set {
                this.fileFormatField = value;
                this.RaisePropertyChanged("FileFormat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum FileFormatEnum {
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        TXT,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        DOCX,
        
        /// <remarks/>
        XLSX,
        
        /// <remarks/>
        XLS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeclPdfEn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string busiUnitField;
        
        private string declarationCodeField;
        
        private byte[] pDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusiUnit {
            get {
                return this.busiUnitField;
            }
            set {
                this.busiUnitField = value;
                this.RaisePropertyChanged("BusiUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DeclarationCode {
            get {
                return this.declarationCodeField;
            }
            set {
                this.declarationCodeField = value;
                this.RaisePropertyChanged("DeclarationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
                this.RaisePropertyChanged("PDF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeclListEn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> oRDERNOField;
        
        private string iTEMNOField;
        
        private string cOMMODITYNOField;
        
        private string aDDITIONALNOField;
        
        private string cOMMODITYNAMEField;
        
        private string sPECIFICATIONSMODELField;
        
        private System.Nullable<decimal> lEGALQUANTITYField;
        
        private string lEGALUNITField;
        
        private System.Nullable<decimal> sQUANTITYField;
        
        private string sUNITField;
        
        private System.Nullable<decimal> cADQUANTITYField;
        
        private string cADUNITField;
        
        private System.Nullable<decimal> uNITPRICEField;
        
        private System.Nullable<decimal> tOTALPRICEField;
        
        private string cURRENCYField;
        
        private string cURRENCYCODEField;
        
        private string tAXPAIDField;
        
        private string vERSIONNOField;
        
        private string aRTNOField;
        
        private System.Nullable<decimal> pROCESSINGFEESField;
        
        private System.Nullable<decimal> gOODSNWField;
        
        private string lICENSENOField;
        
        private string iSOUEQUIPMENTField;
        
        private string iSWASTEMATERIALSField;
        
        private string iSFORCELAWCONDITIONField;
        
        private string pURPOSEField;
        
        private string cUSTOMREGULATORYField;
        
        private string iNSPECTIONREGULATORYField;
        
        private string cIQCODEField;
        
        private System.Nullable<decimal> cREATEBYField;
        
        private System.Nullable<System.DateTime> cREATEDATEField;
        
        private string pREDECLCODEField;
        
        private string cOUNTRYORIGINField;
        
        private string cOUNTRYORIGINCODEField;
        
        private string uNITYCODEField;
        
        private System.Nullable<decimal> iSSPECIALField;
        
        private string dESTCOUNTRYCODEField;
        
        private string dESTCOUNTRYNAMEField;
        
        private System.Nullable<System.DateTime> iNOUTDATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> ORDERNO {
            get {
                return this.oRDERNOField;
            }
            set {
                this.oRDERNOField = value;
                this.RaisePropertyChanged("ORDERNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ITEMNO {
            get {
                return this.iTEMNOField;
            }
            set {
                this.iTEMNOField = value;
                this.RaisePropertyChanged("ITEMNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COMMODITYNO {
            get {
                return this.cOMMODITYNOField;
            }
            set {
                this.cOMMODITYNOField = value;
                this.RaisePropertyChanged("COMMODITYNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ADDITIONALNO {
            get {
                return this.aDDITIONALNOField;
            }
            set {
                this.aDDITIONALNOField = value;
                this.RaisePropertyChanged("ADDITIONALNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string COMMODITYNAME {
            get {
                return this.cOMMODITYNAMEField;
            }
            set {
                this.cOMMODITYNAMEField = value;
                this.RaisePropertyChanged("COMMODITYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SPECIFICATIONSMODEL {
            get {
                return this.sPECIFICATIONSMODELField;
            }
            set {
                this.sPECIFICATIONSMODELField = value;
                this.RaisePropertyChanged("SPECIFICATIONSMODEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> LEGALQUANTITY {
            get {
                return this.lEGALQUANTITYField;
            }
            set {
                this.lEGALQUANTITYField = value;
                this.RaisePropertyChanged("LEGALQUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LEGALUNIT {
            get {
                return this.lEGALUNITField;
            }
            set {
                this.lEGALUNITField = value;
                this.RaisePropertyChanged("LEGALUNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> SQUANTITY {
            get {
                return this.sQUANTITYField;
            }
            set {
                this.sQUANTITYField = value;
                this.RaisePropertyChanged("SQUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SUNIT {
            get {
                return this.sUNITField;
            }
            set {
                this.sUNITField = value;
                this.RaisePropertyChanged("SUNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> CADQUANTITY {
            get {
                return this.cADQUANTITYField;
            }
            set {
                this.cADQUANTITYField = value;
                this.RaisePropertyChanged("CADQUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CADUNIT {
            get {
                return this.cADUNITField;
            }
            set {
                this.cADUNITField = value;
                this.RaisePropertyChanged("CADUNIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> UNITPRICE {
            get {
                return this.uNITPRICEField;
            }
            set {
                this.uNITPRICEField = value;
                this.RaisePropertyChanged("UNITPRICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> TOTALPRICE {
            get {
                return this.tOTALPRICEField;
            }
            set {
                this.tOTALPRICEField = value;
                this.RaisePropertyChanged("TOTALPRICE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CURRENCY {
            get {
                return this.cURRENCYField;
            }
            set {
                this.cURRENCYField = value;
                this.RaisePropertyChanged("CURRENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CURRENCYCODE {
            get {
                return this.cURRENCYCODEField;
            }
            set {
                this.cURRENCYCODEField = value;
                this.RaisePropertyChanged("CURRENCYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TAXPAID {
            get {
                return this.tAXPAIDField;
            }
            set {
                this.tAXPAIDField = value;
                this.RaisePropertyChanged("TAXPAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string VERSIONNO {
            get {
                return this.vERSIONNOField;
            }
            set {
                this.vERSIONNOField = value;
                this.RaisePropertyChanged("VERSIONNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ARTNO {
            get {
                return this.aRTNOField;
            }
            set {
                this.aRTNOField = value;
                this.RaisePropertyChanged("ARTNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> PROCESSINGFEES {
            get {
                return this.pROCESSINGFEESField;
            }
            set {
                this.pROCESSINGFEESField = value;
                this.RaisePropertyChanged("PROCESSINGFEES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<decimal> GOODSNW {
            get {
                return this.gOODSNWField;
            }
            set {
                this.gOODSNWField = value;
                this.RaisePropertyChanged("GOODSNW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string LICENSENO {
            get {
                return this.lICENSENOField;
            }
            set {
                this.lICENSENOField = value;
                this.RaisePropertyChanged("LICENSENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ISOUEQUIPMENT {
            get {
                return this.iSOUEQUIPMENTField;
            }
            set {
                this.iSOUEQUIPMENTField = value;
                this.RaisePropertyChanged("ISOUEQUIPMENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ISWASTEMATERIALS {
            get {
                return this.iSWASTEMATERIALSField;
            }
            set {
                this.iSWASTEMATERIALSField = value;
                this.RaisePropertyChanged("ISWASTEMATERIALS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ISFORCELAWCONDITION {
            get {
                return this.iSFORCELAWCONDITIONField;
            }
            set {
                this.iSFORCELAWCONDITIONField = value;
                this.RaisePropertyChanged("ISFORCELAWCONDITION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PURPOSE {
            get {
                return this.pURPOSEField;
            }
            set {
                this.pURPOSEField = value;
                this.RaisePropertyChanged("PURPOSE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CUSTOMREGULATORY {
            get {
                return this.cUSTOMREGULATORYField;
            }
            set {
                this.cUSTOMREGULATORYField = value;
                this.RaisePropertyChanged("CUSTOMREGULATORY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string INSPECTIONREGULATORY {
            get {
                return this.iNSPECTIONREGULATORYField;
            }
            set {
                this.iNSPECTIONREGULATORYField = value;
                this.RaisePropertyChanged("INSPECTIONREGULATORY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CIQCODE {
            get {
                return this.cIQCODEField;
            }
            set {
                this.cIQCODEField = value;
                this.RaisePropertyChanged("CIQCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<decimal> CREATEBY {
            get {
                return this.cREATEBYField;
            }
            set {
                this.cREATEBYField = value;
                this.RaisePropertyChanged("CREATEBY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<System.DateTime> CREATEDATE {
            get {
                return this.cREATEDATEField;
            }
            set {
                this.cREATEDATEField = value;
                this.RaisePropertyChanged("CREATEDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string PREDECLCODE {
            get {
                return this.pREDECLCODEField;
            }
            set {
                this.pREDECLCODEField = value;
                this.RaisePropertyChanged("PREDECLCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string COUNTRYORIGIN {
            get {
                return this.cOUNTRYORIGINField;
            }
            set {
                this.cOUNTRYORIGINField = value;
                this.RaisePropertyChanged("COUNTRYORIGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string COUNTRYORIGINCODE {
            get {
                return this.cOUNTRYORIGINCODEField;
            }
            set {
                this.cOUNTRYORIGINCODEField = value;
                this.RaisePropertyChanged("COUNTRYORIGINCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string UNITYCODE {
            get {
                return this.uNITYCODEField;
            }
            set {
                this.uNITYCODEField = value;
                this.RaisePropertyChanged("UNITYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<decimal> ISSPECIAL {
            get {
                return this.iSSPECIALField;
            }
            set {
                this.iSSPECIALField = value;
                this.RaisePropertyChanged("ISSPECIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string DESTCOUNTRYCODE {
            get {
                return this.dESTCOUNTRYCODEField;
            }
            set {
                this.dESTCOUNTRYCODEField = value;
                this.RaisePropertyChanged("DESTCOUNTRYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string DESTCOUNTRYNAME {
            get {
                return this.dESTCOUNTRYNAMEField;
            }
            set {
                this.dESTCOUNTRYNAMEField = value;
                this.RaisePropertyChanged("DESTCOUNTRYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<System.DateTime> INOUTDATE {
            get {
                return this.iNOUTDATEField;
            }
            set {
                this.iNOUTDATEField = value;
                this.RaisePropertyChanged("INOUTDATE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeclarationEn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> repStartTimeField;
        
        private DeclListEn[] subDeclListField;
        
        private decimal idField;
        
        private string cODEField;
        
        private string oRDERCODEField;
        
        private string dECLARATIONCODEField;
        
        private string uNITYCODEField;
        
        private string cURRENTCODEField;
        
        private string cUSTOMAREACODEField;
        
        private string dECLWAYField;
        
        private string dECLTYPEField;
        
        private string pORTCODEField;
        
        private string cONTRACTNOField;
        
        private string rECORDCODEField;
        
        private string cHANNELField;
        
        private string cONSHIPPERCODEField;
        
        private string cONSHIPPERNAMEField;
        
        private string bUSIUNITCODEField;
        
        private string bUSIUNITNAMEField;
        
        private string rEPUNITCODEField;
        
        private string rEPUNITNAMEField;
        
        private string tRANSMODELField;
        
        private string tRANSNAMEField;
        
        private string vOYAGENOField;
        
        private string bLNOField;
        
        private string eXEMPTIONCODEField;
        
        private string tRADECODEField;
        
        private string tRADECOUNTRYCODEField;
        
        private string sECOUNTRYCODEField;
        
        private string sEPORTCODEField;
        
        private string sEPLACECODEField;
        
        private System.Nullable<decimal> gOODSNUMField;
        
        private string pACKAGECODEField;
        
        private string lICENSENOField;
        
        private System.Nullable<decimal> gOODSGWField;
        
        private System.Nullable<decimal> gOODSNWField;
        
        private string tRADETERMSCODEField;
        
        private string fGCODEField;
        
        private System.Nullable<decimal> fREIGHTField;
        
        private string fGUNITCODEField;
        
        private string iPCODEField;
        
        private System.Nullable<decimal> iNSURANCEPREMIUMField;
        
        private string iPUNITCODEField;
        
        private string aECODEField;
        
        private System.Nullable<decimal> aDDITIONALEXPENSESField;
        
        private string aEUNITCODEField;
        
        private System.Nullable<decimal> sPECIALRELATIONField;
        
        private System.Nullable<decimal> pRICEIMPACTField;
        
        private System.Nullable<decimal> pAYPOYALTIESField;
        
        private System.Nullable<decimal> tAXRATEField;
        
        private string tAXUNITCODEField;
        
        private string tAXUNITNAMEField;
        
        private string lISTINFOField;
        
        private string rEMARKField;
        
        private string cONSHIPPERNUMField;
        
        private string bUSIUNITNUMField;
        
        private string rEPUNITNUMField;
        
        private System.Nullable<decimal> iSNEEDCLEARANCEField;
        
        private System.Nullable<decimal> iSHAVECLEARANCEField;
        
        private System.Nullable<decimal> iSFORCELAWField;
        
        private string wAREHOUSENOField;
        
        private string yARDCODEField;
        
        private System.Nullable<decimal> sHEETNUMField;
        
        private System.Nullable<decimal> pRESHEETNUMField;
        
        private System.Nullable<decimal> cOMMODITYNUMField;
        
        private string cUSNOField;
        
        private string rEPWAYIDField;
        
        private string cUSTOMSSTATUSField;
        
        private System.Nullable<decimal> tOTALNWField;
        
        private System.Nullable<decimal> tOTALMONEYField;
        
        private System.Nullable<decimal> tOTALNUMField;
        
        private string lISTTYPEField;
        
        private System.Nullable<decimal> fORMATAUTOField;
        
        private string aSSOCIATEPEDECLNOField;
        
        private string aSSOCIATEDECLNOField;
        
        private System.Nullable<decimal> dECLCODESOURCEField;
        
        private string dECLREMARKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> RepStartTime {
            get {
                return this.repStartTimeField;
            }
            set {
                this.repStartTimeField = value;
                this.RaisePropertyChanged("RepStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public DeclListEn[] SubDeclList {
            get {
                return this.subDeclListField;
            }
            set {
                this.subDeclListField = value;
                this.RaisePropertyChanged("SubDeclList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ORDERCODE {
            get {
                return this.oRDERCODEField;
            }
            set {
                this.oRDERCODEField = value;
                this.RaisePropertyChanged("ORDERCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DECLARATIONCODE {
            get {
                return this.dECLARATIONCODEField;
            }
            set {
                this.dECLARATIONCODEField = value;
                this.RaisePropertyChanged("DECLARATIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UNITYCODE {
            get {
                return this.uNITYCODEField;
            }
            set {
                this.uNITYCODEField = value;
                this.RaisePropertyChanged("UNITYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CURRENTCODE {
            get {
                return this.cURRENTCODEField;
            }
            set {
                this.cURRENTCODEField = value;
                this.RaisePropertyChanged("CURRENTCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CUSTOMAREACODE {
            get {
                return this.cUSTOMAREACODEField;
            }
            set {
                this.cUSTOMAREACODEField = value;
                this.RaisePropertyChanged("CUSTOMAREACODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DECLWAY {
            get {
                return this.dECLWAYField;
            }
            set {
                this.dECLWAYField = value;
                this.RaisePropertyChanged("DECLWAY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DECLTYPE {
            get {
                return this.dECLTYPEField;
            }
            set {
                this.dECLTYPEField = value;
                this.RaisePropertyChanged("DECLTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PORTCODE {
            get {
                return this.pORTCODEField;
            }
            set {
                this.pORTCODEField = value;
                this.RaisePropertyChanged("PORTCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CONTRACTNO {
            get {
                return this.cONTRACTNOField;
            }
            set {
                this.cONTRACTNOField = value;
                this.RaisePropertyChanged("CONTRACTNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RECORDCODE {
            get {
                return this.rECORDCODEField;
            }
            set {
                this.rECORDCODEField = value;
                this.RaisePropertyChanged("RECORDCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CHANNEL {
            get {
                return this.cHANNELField;
            }
            set {
                this.cHANNELField = value;
                this.RaisePropertyChanged("CHANNEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CONSHIPPERCODE {
            get {
                return this.cONSHIPPERCODEField;
            }
            set {
                this.cONSHIPPERCODEField = value;
                this.RaisePropertyChanged("CONSHIPPERCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CONSHIPPERNAME {
            get {
                return this.cONSHIPPERNAMEField;
            }
            set {
                this.cONSHIPPERNAMEField = value;
                this.RaisePropertyChanged("CONSHIPPERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string BUSIUNITCODE {
            get {
                return this.bUSIUNITCODEField;
            }
            set {
                this.bUSIUNITCODEField = value;
                this.RaisePropertyChanged("BUSIUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string BUSIUNITNAME {
            get {
                return this.bUSIUNITNAMEField;
            }
            set {
                this.bUSIUNITNAMEField = value;
                this.RaisePropertyChanged("BUSIUNITNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string REPUNITCODE {
            get {
                return this.rEPUNITCODEField;
            }
            set {
                this.rEPUNITCODEField = value;
                this.RaisePropertyChanged("REPUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string REPUNITNAME {
            get {
                return this.rEPUNITNAMEField;
            }
            set {
                this.rEPUNITNAMEField = value;
                this.RaisePropertyChanged("REPUNITNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TRANSMODEL {
            get {
                return this.tRANSMODELField;
            }
            set {
                this.tRANSMODELField = value;
                this.RaisePropertyChanged("TRANSMODEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string TRANSNAME {
            get {
                return this.tRANSNAMEField;
            }
            set {
                this.tRANSNAMEField = value;
                this.RaisePropertyChanged("TRANSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string VOYAGENO {
            get {
                return this.vOYAGENOField;
            }
            set {
                this.vOYAGENOField = value;
                this.RaisePropertyChanged("VOYAGENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BLNO {
            get {
                return this.bLNOField;
            }
            set {
                this.bLNOField = value;
                this.RaisePropertyChanged("BLNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string EXEMPTIONCODE {
            get {
                return this.eXEMPTIONCODEField;
            }
            set {
                this.eXEMPTIONCODEField = value;
                this.RaisePropertyChanged("EXEMPTIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string TRADECODE {
            get {
                return this.tRADECODEField;
            }
            set {
                this.tRADECODEField = value;
                this.RaisePropertyChanged("TRADECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string TRADECOUNTRYCODE {
            get {
                return this.tRADECOUNTRYCODEField;
            }
            set {
                this.tRADECOUNTRYCODEField = value;
                this.RaisePropertyChanged("TRADECOUNTRYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SECOUNTRYCODE {
            get {
                return this.sECOUNTRYCODEField;
            }
            set {
                this.sECOUNTRYCODEField = value;
                this.RaisePropertyChanged("SECOUNTRYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string SEPORTCODE {
            get {
                return this.sEPORTCODEField;
            }
            set {
                this.sEPORTCODEField = value;
                this.RaisePropertyChanged("SEPORTCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string SEPLACECODE {
            get {
                return this.sEPLACECODEField;
            }
            set {
                this.sEPLACECODEField = value;
                this.RaisePropertyChanged("SEPLACECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<decimal> GOODSNUM {
            get {
                return this.gOODSNUMField;
            }
            set {
                this.gOODSNUMField = value;
                this.RaisePropertyChanged("GOODSNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string PACKAGECODE {
            get {
                return this.pACKAGECODEField;
            }
            set {
                this.pACKAGECODEField = value;
                this.RaisePropertyChanged("PACKAGECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string LICENSENO {
            get {
                return this.lICENSENOField;
            }
            set {
                this.lICENSENOField = value;
                this.RaisePropertyChanged("LICENSENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<decimal> GOODSGW {
            get {
                return this.gOODSGWField;
            }
            set {
                this.gOODSGWField = value;
                this.RaisePropertyChanged("GOODSGW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<decimal> GOODSNW {
            get {
                return this.gOODSNWField;
            }
            set {
                this.gOODSNWField = value;
                this.RaisePropertyChanged("GOODSNW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string TRADETERMSCODE {
            get {
                return this.tRADETERMSCODEField;
            }
            set {
                this.tRADETERMSCODEField = value;
                this.RaisePropertyChanged("TRADETERMSCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string FGCODE {
            get {
                return this.fGCODEField;
            }
            set {
                this.fGCODEField = value;
                this.RaisePropertyChanged("FGCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<decimal> FREIGHT {
            get {
                return this.fREIGHTField;
            }
            set {
                this.fREIGHTField = value;
                this.RaisePropertyChanged("FREIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string FGUNITCODE {
            get {
                return this.fGUNITCODEField;
            }
            set {
                this.fGUNITCODEField = value;
                this.RaisePropertyChanged("FGUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string IPCODE {
            get {
                return this.iPCODEField;
            }
            set {
                this.iPCODEField = value;
                this.RaisePropertyChanged("IPCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<decimal> INSURANCEPREMIUM {
            get {
                return this.iNSURANCEPREMIUMField;
            }
            set {
                this.iNSURANCEPREMIUMField = value;
                this.RaisePropertyChanged("INSURANCEPREMIUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string IPUNITCODE {
            get {
                return this.iPUNITCODEField;
            }
            set {
                this.iPUNITCODEField = value;
                this.RaisePropertyChanged("IPUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string AECODE {
            get {
                return this.aECODEField;
            }
            set {
                this.aECODEField = value;
                this.RaisePropertyChanged("AECODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public System.Nullable<decimal> ADDITIONALEXPENSES {
            get {
                return this.aDDITIONALEXPENSESField;
            }
            set {
                this.aDDITIONALEXPENSESField = value;
                this.RaisePropertyChanged("ADDITIONALEXPENSES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string AEUNITCODE {
            get {
                return this.aEUNITCODEField;
            }
            set {
                this.aEUNITCODEField = value;
                this.RaisePropertyChanged("AEUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public System.Nullable<decimal> SPECIALRELATION {
            get {
                return this.sPECIALRELATIONField;
            }
            set {
                this.sPECIALRELATIONField = value;
                this.RaisePropertyChanged("SPECIALRELATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public System.Nullable<decimal> PRICEIMPACT {
            get {
                return this.pRICEIMPACTField;
            }
            set {
                this.pRICEIMPACTField = value;
                this.RaisePropertyChanged("PRICEIMPACT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public System.Nullable<decimal> PAYPOYALTIES {
            get {
                return this.pAYPOYALTIESField;
            }
            set {
                this.pAYPOYALTIESField = value;
                this.RaisePropertyChanged("PAYPOYALTIES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public System.Nullable<decimal> TAXRATE {
            get {
                return this.tAXRATEField;
            }
            set {
                this.tAXRATEField = value;
                this.RaisePropertyChanged("TAXRATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string TAXUNITCODE {
            get {
                return this.tAXUNITCODEField;
            }
            set {
                this.tAXUNITCODEField = value;
                this.RaisePropertyChanged("TAXUNITCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string TAXUNITNAME {
            get {
                return this.tAXUNITNAMEField;
            }
            set {
                this.tAXUNITNAMEField = value;
                this.RaisePropertyChanged("TAXUNITNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string LISTINFO {
            get {
                return this.lISTINFOField;
            }
            set {
                this.lISTINFOField = value;
                this.RaisePropertyChanged("LISTINFO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string CONSHIPPERNUM {
            get {
                return this.cONSHIPPERNUMField;
            }
            set {
                this.cONSHIPPERNUMField = value;
                this.RaisePropertyChanged("CONSHIPPERNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string BUSIUNITNUM {
            get {
                return this.bUSIUNITNUMField;
            }
            set {
                this.bUSIUNITNUMField = value;
                this.RaisePropertyChanged("BUSIUNITNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string REPUNITNUM {
            get {
                return this.rEPUNITNUMField;
            }
            set {
                this.rEPUNITNUMField = value;
                this.RaisePropertyChanged("REPUNITNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=57)]
        public System.Nullable<decimal> ISNEEDCLEARANCE {
            get {
                return this.iSNEEDCLEARANCEField;
            }
            set {
                this.iSNEEDCLEARANCEField = value;
                this.RaisePropertyChanged("ISNEEDCLEARANCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=58)]
        public System.Nullable<decimal> ISHAVECLEARANCE {
            get {
                return this.iSHAVECLEARANCEField;
            }
            set {
                this.iSHAVECLEARANCEField = value;
                this.RaisePropertyChanged("ISHAVECLEARANCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=59)]
        public System.Nullable<decimal> ISFORCELAW {
            get {
                return this.iSFORCELAWField;
            }
            set {
                this.iSFORCELAWField = value;
                this.RaisePropertyChanged("ISFORCELAW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string WAREHOUSENO {
            get {
                return this.wAREHOUSENOField;
            }
            set {
                this.wAREHOUSENOField = value;
                this.RaisePropertyChanged("WAREHOUSENO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string YARDCODE {
            get {
                return this.yARDCODEField;
            }
            set {
                this.yARDCODEField = value;
                this.RaisePropertyChanged("YARDCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=62)]
        public System.Nullable<decimal> SHEETNUM {
            get {
                return this.sHEETNUMField;
            }
            set {
                this.sHEETNUMField = value;
                this.RaisePropertyChanged("SHEETNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=63)]
        public System.Nullable<decimal> PRESHEETNUM {
            get {
                return this.pRESHEETNUMField;
            }
            set {
                this.pRESHEETNUMField = value;
                this.RaisePropertyChanged("PRESHEETNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=64)]
        public System.Nullable<decimal> COMMODITYNUM {
            get {
                return this.cOMMODITYNUMField;
            }
            set {
                this.cOMMODITYNUMField = value;
                this.RaisePropertyChanged("COMMODITYNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string CUSNO {
            get {
                return this.cUSNOField;
            }
            set {
                this.cUSNOField = value;
                this.RaisePropertyChanged("CUSNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string REPWAYID {
            get {
                return this.rEPWAYIDField;
            }
            set {
                this.rEPWAYIDField = value;
                this.RaisePropertyChanged("REPWAYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string CUSTOMSSTATUS {
            get {
                return this.cUSTOMSSTATUSField;
            }
            set {
                this.cUSTOMSSTATUSField = value;
                this.RaisePropertyChanged("CUSTOMSSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=68)]
        public System.Nullable<decimal> TOTALNW {
            get {
                return this.tOTALNWField;
            }
            set {
                this.tOTALNWField = value;
                this.RaisePropertyChanged("TOTALNW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=69)]
        public System.Nullable<decimal> TOTALMONEY {
            get {
                return this.tOTALMONEYField;
            }
            set {
                this.tOTALMONEYField = value;
                this.RaisePropertyChanged("TOTALMONEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=70)]
        public System.Nullable<decimal> TOTALNUM {
            get {
                return this.tOTALNUMField;
            }
            set {
                this.tOTALNUMField = value;
                this.RaisePropertyChanged("TOTALNUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string LISTTYPE {
            get {
                return this.lISTTYPEField;
            }
            set {
                this.lISTTYPEField = value;
                this.RaisePropertyChanged("LISTTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=72)]
        public System.Nullable<decimal> FORMATAUTO {
            get {
                return this.fORMATAUTOField;
            }
            set {
                this.fORMATAUTOField = value;
                this.RaisePropertyChanged("FORMATAUTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string ASSOCIATEPEDECLNO {
            get {
                return this.aSSOCIATEPEDECLNOField;
            }
            set {
                this.aSSOCIATEPEDECLNOField = value;
                this.RaisePropertyChanged("ASSOCIATEPEDECLNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string ASSOCIATEDECLNO {
            get {
                return this.aSSOCIATEDECLNOField;
            }
            set {
                this.aSSOCIATEDECLNOField = value;
                this.RaisePropertyChanged("ASSOCIATEDECLNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=75)]
        public System.Nullable<decimal> DECLCODESOURCE {
            get {
                return this.dECLCODESOURCEField;
            }
            set {
                this.dECLCODESOURCEField = value;
                this.RaisePropertyChanged("DECLCODESOURCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public string DECLREMARK {
            get {
                return this.dECLREMARKField;
            }
            set {
                this.dECLREMARKField = value;
                this.RaisePropertyChanged("DECLREMARK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeclStatusEn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string repNoField;
        
        private string busiUnitField;
        
        private string declarationCodeField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RepNo {
            get {
                return this.repNoField;
            }
            set {
                this.repNoField = value;
                this.RaisePropertyChanged("RepNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusiUnit {
            get {
                return this.busiUnitField;
            }
            set {
                this.busiUnitField = value;
                this.RaisePropertyChanged("BusiUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DeclarationCode {
            get {
                return this.declarationCodeField;
            }
            set {
                this.declarationCodeField = value;
                this.RaisePropertyChanged("DeclarationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceSoapChannel : SceneOfCustoms.ServiceReference1.CustomerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<SceneOfCustoms.ServiceReference1.CustomerServiceSoap>, SceneOfCustoms.ServiceReference1.CustomerServiceSoap {
        
        public CustomerServiceSoapClient() {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendOrderData(SceneOfCustoms.ServiceReference1.OrderEn[] list) {
            return base.Channel.SendOrderData(list);
        }
        
        public System.Threading.Tasks.Task<string> SendOrderDataAsync(SceneOfCustoms.ServiceReference1.OrderEn[] list) {
            return base.Channel.SendOrderDataAsync(list);
        }
        
        public SceneOfCustoms.ServiceReference1.DeclStatusEn[] ReceiveDeclarationStatus(string repno, string busiUnit) {
            return base.Channel.ReceiveDeclarationStatus(repno, busiUnit);
        }
        
        public System.Threading.Tasks.Task<SceneOfCustoms.ServiceReference1.DeclStatusEn[]> ReceiveDeclarationStatusAsync(string repno, string busiUnit) {
            return base.Channel.ReceiveDeclarationStatusAsync(repno, busiUnit);
        }
        
        public SceneOfCustoms.ServiceReference1.DeclarationEn[] ReceiveDeclaration(string repno, string busiUnit) {
            return base.Channel.ReceiveDeclaration(repno, busiUnit);
        }
        
        public System.Threading.Tasks.Task<SceneOfCustoms.ServiceReference1.DeclarationEn[]> ReceiveDeclarationAsync(string repno, string busiUnit) {
            return base.Channel.ReceiveDeclarationAsync(repno, busiUnit);
        }
        
        public SceneOfCustoms.ServiceReference1.DeclPdfEn[] ReceiveDeclarationPdf(string repno, string busiUnit) {
            return base.Channel.ReceiveDeclarationPdf(repno, busiUnit);
        }
        
        public System.Threading.Tasks.Task<SceneOfCustoms.ServiceReference1.DeclPdfEn[]> ReceiveDeclarationPdfAsync(string repno, string busiUnit) {
            return base.Channel.ReceiveDeclarationPdfAsync(repno, busiUnit);
        }
    }
}
